quarkus:
  datasource:
    db-kind: postgresql
    devservices:
      enabled: false
    reactive:
      url: postgresql://root:123@localhost:5434/quarkus
  hibernate-orm:
    database:
      generation: drop-and-create

kafka:
  bootstrap:
    servers: localhost:9092

mp:
  messaging:
    outgoing:
      delivery-events:
        connector: smallrye-kafka
        topic: deliveries.v1.events
        value:
          serializer: br.com.elvisassis.infrastructure.messaging.JsonObjectSerializer
        key:
          serializer: org.apache.kafka.common.serialization.StringSerializer

topics:
  - name: deliveries.v1.events
    partitions: 3
    replicas: 1
  - name: entregas
    partitions: 2
    replicas: 1
  - name: pagamentos
    partitions: 3
    replicas: 1


